id: P004644
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ294443
  title: ཐུབ་དབང་འཁོར་བཅས་མཆོད་པའི་ཆོ་ག་བཀལག་ཆོག་ཏུ་འགྲིགས་པ།
  author: ''
  volumes:
    b01eb50e9ea24b9ea6f83beedef5cc4e:
      image_group_id: I4CZ294559
      title: ''
      volume_number: 1
      total_pages: 462
