id: IB4F6F3AB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T20:46:59+00:00'
last_modified: '2022-06-08T02:32:31.375475+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ294443
  title: ཐུབ་དབང་འཁོར་བཅས་མཆོད་པའི་ཆོ་ག་བཀལག་ཆོག་ཏུ་འགྲིགས་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E28B:
      image_group_id: I4CZ294559
      title: ''
      total_pages: 462
      order: 1
      base_file: E28B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
