id: IB4F6F3AB
legacy_id: P004644
ocr_import_info:
  bdrc_scan_id: W4CZ294443
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T20:44:06'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T18:28:13.422823+00:00'
last_modified: 2022-09-04 02:28:24.319380
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4CZ294443
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW4CZ294443
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཐུབ་དབང་འཁོར་བཅས་མཆོད་པའི་ཆོ་ག་བཀླག་ཆོག་ཏུ་འགྲིགས་པ།
statistics:
  ocr_word_mean_confidence_index: 0.9129897436643616
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I4CZ294559:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ294559
      total_pages: 462
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4CZ294559.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9129897436643616
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
